#!/usr/bin/env Rscript
# Build an appendix table of the test ground-truth papers.
#
# For every paper ID in tests/test_papers.csv this reads the GROBID TEI XML in
# expanded_xml/, extracts paper title, authors, document DOI, and the OSF link,
# then writes both a CSV and a multi-page LaTeX longtable for the thesis appendix.
#
# OSF-link extraction uses the same metacheck path as pipeline/0_index.R
# (read() + osf_links(), filtering BADGE_REPOS) so results are reproducible.
#
# Usage:  Rscript runners/analysis/build_appendix_table.R

suppressMessages(library(metacheck))

`%||%` <- function(a, b) if (is.null(a)) b else a

# ── Paths ─────────────────────────────────────────────────────────────────────
ROOT       <- "/Volumes/Models/dev/datacheck"
# Ground-truth set: one <id>.csv per paper in datacheck. This defines the ID list.
GT_DIR     <- file.path(ROOT, "tests", "ground_truth", "osf")
# TEI XML is resolved across BOTH dirs (grobid 0.8.2 first, expanded_xml
# fallback) so every id finds a file to read links/title/authors from.
XML_DIRS   <- c("/Users/levibaruch/dev/metacheck/data-raw/psychsci/grobid_0.8.2-full",
                "/Volumes/Models/expanded_xml")
OUT_CSV    <- file.path(ROOT, "docs", "appendix_paper_table.csv")
OUT_TEX    <- file.path(ROOT, "docs", "appendix_paper_table.tex")

# Mirror pipeline/0_index.R: badge wiki link, never a data repo.
BADGE_REPOS <- c("tvyxz", "osf.io/tvyxz/", "osf.io/tvyxz")

# ── Helpers ───────────────────────────────────────────────────────────────────

# "Given Surname; Given Surname; ..." from a scivrs_authors list.
format_authors <- function(authors) {
  if (is.null(authors) || length(authors) == 0) return(NA_character_)
  nm <- vapply(authors, function(a) {
    given   <- a$name$given   %||% ""
    surname <- a$name$surname %||% ""
    trimws(paste(given, surname))
  }, character(1))
  nm <- nm[nzchar(nm)]
  if (length(nm) == 0) NA_character_ else paste(nm, collapse = "; ")
}

# Psychological Science DOI from the paper ID (the ID is the DOI suffix).
# GROBID's extracted DOI is unreliable (carries "pss.sagepub" cruft), so we
# derive it canonically: prefix 10.1177/ + id.
doi_from_id <- function(id) paste0("10.1177/", id)

# First non-badge OSF link for the paper, "osf.io/xxxxx".
extract_osf <- function(paper) {
  links <- tryCatch(osf_links(paper), error = function(e) NULL)
  if (is.null(links) || nrow(links) == 0) return(NA_character_)
  cand <- setdiff(unique(links$text), BADGE_REPOS)
  if (length(cand) == 0) return(NA_character_)
  url <- sub("/+$", "", cand[1])
  if (!grepl("^https?://", url)) url <- paste0("https://", url)
  url
}

# Escape LaTeX special characters in free text.
tex_escape <- function(x) {
  if (is.na(x)) return("")
  x <- gsub("\\\\", "\\\\textbackslash{}", x)
  x <- gsub("([&%$#_{}])", "\\\\\\1", x)
  x <- gsub("~", "\\\\textasciitilde{}", x)
  x <- gsub("\\^", "\\\\textasciicircum{}", x)
  x
}

# Emit the multi-page longtable from a data.frame (cols: id,title,author,doi,osf).
write_tex <- function(tab) {
  hdr <- c(
    "% Auto-generated by runners/analysis/build_appendix_table.R",
    "% Requires: \\usepackage{longtable, booktabs, array, hyperref}",
    "\\begingroup",
    "\\footnotesize",
    "\\setlength{\\LTleft}{0pt}\\setlength{\\LTright}{0pt}",
    "\\begin{longtable}{@{}p{5.0cm} p{4.0cm} p{3.4cm} p{2.6cm}@{}}",
    "\\caption{Test ground-truth papers: title, authors, document DOI, and source OSF repository.}\\label{tab:appendix-papers}\\\\",
    "\\toprule",
    "\\textbf{Paper} & \\textbf{Authors} & \\textbf{DOI} & \\textbf{OSF} \\\\",
    "\\midrule",
    "\\endfirsthead",
    "\\multicolumn{4}{c}{\\tablename\\ \\thetable{} -- continued from previous page}\\\\",
    "\\toprule",
    "\\textbf{Paper} & \\textbf{Authors} & \\textbf{DOI} & \\textbf{OSF} \\\\",
    "\\midrule",
    "\\endhead",
    "\\midrule \\multicolumn{4}{r}{\\textit{continued on next page}}\\\\",
    "\\endfoot",
    "\\bottomrule",
    "\\endlastfoot"
  )
  # Allow long DOI digit strings to break: insert \allowbreak between prefix and suffix.
  doi_disp <- function(d) {
    parts <- strsplit(d, "/", fixed = TRUE)[[1]]
    if (length(parts) == 2) paste0(parts[1], "/\\allowbreak ", parts[2]) else d
  }
  body <- vapply(seq_len(nrow(tab)), function(i) {
    r   <- tab[i, ]
    doi <- if (is.na(r$doi) || !nzchar(r$doi)) "" else
      paste0("\\href{https://doi.org/", r$doi, "}{", doi_disp(r$doi), "}")
    osf <- if (is.na(r$osf) || !nzchar(r$osf)) "" else
      paste0("\\href{", r$osf, "}{", sub("^https?://", "", r$osf), "}")
    paste0(
      tex_escape(r$title), " & ",
      tex_escape(r$author), " & ",
      doi, " & ",
      osf, " \\\\\\addlinespace[6pt]"
    )
  }, character(1))
  writeLines(c(hdr, body, "\\end{longtable}", "\\endgroup"), OUT_TEX)
  message("Wrote ", OUT_TEX, " (", nrow(tab), " rows)")
}

# ── tex-only mode: rebuild .tex from a hand-edited .csv, no XML reading ────────
args <- commandArgs(trailingOnly = TRUE)
if (length(args) && args[1] %in% c("tex", "--from-csv", "--tex")) {
  if (!file.exists(OUT_CSV)) stop("no CSV to read at ", OUT_CSV)
  tab <- read.csv(OUT_CSV, stringsAsFactors = FALSE, colClasses = "character")
  message("Regenerating TeX from ", OUT_CSV, " (", nrow(tab), " rows)")
  write_tex(tab)
  quit(save = "no", status = 0)
}

# ── Build the table ───────────────────────────────────────────────────────────

# Resolve <id>.xml across XML_DIRS in order; NA if found in none.
find_xml <- function(id) {
  for (d in XML_DIRS) {
    p <- file.path(d, paste0(id, ".xml"))
    if (file.exists(p)) return(p)
  }
  NA_character_
}

ids <- sort(tools::file_path_sans_ext(list.files(GT_DIR, pattern = "\\.csv$")))
n   <- length(ids)
message("Ground-truth set: ", n, " papers from ", GT_DIR)
message("XML search path: ", paste(XML_DIRS, collapse = " -> "))
message(strrep("-", 60))

rows <- lapply(seq_along(ids), function(i) {
  id  <- ids[i]
  tag <- sprintf("[%3d/%d] %s", i, n, id)
  xml_path <- find_xml(id)
  if (is.na(xml_path)) {
    message(tag, "  MISSING XML")
    return(data.frame(id = id, title = NA, author = NA, doi = NA, osf = NA,
                      stringsAsFactors = FALSE))
  }
  paper <- tryCatch(read(xml_path), error = function(e) NULL)
  if (is.null(paper)) {
    message(tag, "  READ FAILED (", basename(dirname(xml_path)), ")")
    return(data.frame(id = id, title = NA, author = NA, doi = NA, osf = NA,
                      stringsAsFactors = FALSE))
  }
  osf <- extract_osf(paper)
  message(tag, "  ", basename(dirname(xml_path)),
          "  osf=", if (is.na(osf)) "NONE" else osf)
  data.frame(
    id     = id,
    title  = paper$info$title %||% NA_character_,
    author = format_authors(paper$authors),
    doi    = doi_from_id(id),
    osf    = osf,
    stringsAsFactors = FALSE
  )
})
tab <- do.call(rbind, rows)

# ── Summary ───────────────────────────────────────────────────────────────────
message(strrep("-", 60))
message("Papers processed : ", nrow(tab))
message("Missing XML      : ", sum(is.na(tab$title) & is.na(tab$osf)))
message("No OSF link      : ", sum(is.na(tab$osf)))
message("With OSF link    : ", sum(!is.na(tab$osf)))

# ── CSV output ────────────────────────────────────────────────────────────────
write.csv(tab, OUT_CSV, row.names = FALSE)
message("Wrote ", OUT_CSV, " (", nrow(tab), " rows)")

# ── LaTeX longtable output ────────────────────────────────────────────────────
write_tex(tab)
