# export_prompts_appendix.R
# Generates docs/appendix_prompts.tex from pipeline/prompts.R.
# Re-run whenever prompts change.

source("pipeline/prompts.R")

OUT_PATH <- "docs/appendix_prompts.tex"

# ── helpers ───────────────────────────────────────────────────────────────────

# Replace Unicode chars that lstlisting cannot handle with ASCII equivalents.
sanitize <- function(x) {
  x <- gsub("—", "--",  x)   # em dash
  x <- gsub("–", "--",  x)   # en dash
  x <- gsub("→", "->",  x)   # right arrow
  x <- gsub("─", "-",   x)   # box-drawing horizontal
  x <- gsub("’", "'",   x)   # right single quote
  x <- gsub("‘", "'",   x)   # left single quote
  x <- gsub("“", "\"",  x)   # left double quote
  x <- gsub("”", "\"",  x)   # right double quote
  x
}

lst <- function(..., label = NULL) {
  body <- sanitize(paste0(...))
  cap  <- if (!is.null(label)) paste0(",\n  label={lst:", gsub(" ", "-", tolower(label)), "},\n  caption={", label, "}") else ""
  paste0(
    "\\begin{lstlisting}[%\n",
    "  breaklines=true, breakatwhitespace=true,\n",
    "  basicstyle=\\small\\ttfamily",
    cap,
    "]\n",
    body,
    "\n\\end{lstlisting}\n"
  )
}

sec  <- function(title) paste0("\n\\subsection{", title, "}\n")
sub  <- function(title) paste0("\n\\subsubsection{", title, "}\n")
para <- function(title) paste0("\n\\paragraph{", title, "}\\ \\\\\n")
note <- function(x)     paste0("\\textit{\\small ", x, "}\n\n")

# ── build ─────────────────────────────────────────────────────────────────────

lines <- c(
  "% Auto-generated by runners/tools/export_prompts_appendix.R",
  "% Do not edit by hand -- re-run the script after changing pipeline/prompts.R.",
  "%",
  "% Add to your document preamble:",
  "%   \\usepackage{listings}",
  "",
  "\\lstset{%",
  "  breaklines=true,",
  "  breakatwhitespace=true,",
  "  basicstyle=\\small\\ttfamily,",
  "  columns=fullflexible,",
  "  keepspaces=true",
  "}",
  "",

  # ── 1. Classification prompts ──────────────────────────────────────────────
  sec("Classification Prompts"),
  note("Auto generated by runners/tools/export_prompts_appendix.R."),

  sub("Plaintext"),
  para("Header"),
  lst(SINGLE_HEADER_PLAIN),
  para("Body"),
  lst(STRUCTURE_PROMPT_PLAIN),

  sub("Markdown"),
  para("Header"),
  lst(SINGLE_HEADER_MD),
  para("Body"),
  lst(STRUCTURE_PROMPT_MD),

  sub("JSON"),
  para("Header"),
  lst(SINGLE_HEADER_JSON),
  para("Body"),
  lst(STRUCTURE_PROMPT_JSON),

  # ── 2. Column classification ───────────────────────────────────────────────
  sec("Column Classification"),
  lst(CHAR_COLUMN_TYPE_PROMPT),

  # ── 3. Aggregate classification ────────────────────────────────────────────
  sec("Aggregate Classification"),
  note("Used for aggregate folders (many files sharing one extension)"),

  sub("Plaintext"),
  lst(AGGREGATE_HEADER_PLAIN),

  sub("Markdown"),
  lst(AGGREGATE_HEADER_MD),

  sub("JSON"),
  lst(AGGREGATE_HEADER_JSON),

  # ── 4. Data granularity ────────────────────────────────────────────────────
  sec("Data Granularity Classification"),
  lst(GRANULARITY_PROMPT),

  # ── 5. Codebook parsing ────────────────────────────────────────────────────
  sec("Codebook Parsing"),
  para("Variable extraction"),
  lst(CODEBOOK_PARSE_PROMPT),
  para("Column--codebook matching"),
  lst(COLUMN_MATCH_PROMPT),
  para("Label deduplication"),
  lst(LABEL_MERGE_PROMPT)
)

writeLines(lines, OUT_PATH)
cat(sprintf("Written: %s\n", OUT_PATH))
